### ISSUE TITLE
Export MeteorReduxActionName

### ISSUE THREAD

**Issue by tungv** [zhongqf/meteoredux#1]
Hi @zhongqf.

First of all, I'd like to say that this package is a life saver for me.
I don't know this is a correct way to do, but it works for me

``` jsx
import {
  ADD_TODO,
  REMOVE_TODO,
  COMPLETE_TODO,
  SET_TODOS
} from './../actions/todos';

import { Todos } from 'app/collections'
import { bindReactiveData } from 'meteoredux'

// Meteor actions (either via collections or methods) usually don't change UI state
// so it's normal to return previous state on most actions
function todos(state: Array = [], action: Object) {
  console.log('action', action.type);
  switch (action.type) {
  case ADD_TODO:
    Todos.insert({text: action.text, checked: false})
    return state

  case REMOVE_TODO:
    Todos.remove({_id: action.todo_id})
    return state

  case COMPLETE_TODO:
    Todos.update({_id: action.todo_id})
    return state

  case '@@METEORREDUX/CHANGED':
    return Todos.find({}).fetch()

  default:
    return state
  }
}

export default bindReactiveData(todos, () => {
  return Todos.find({}).fetch()
})

```

I'm using `@@METEORREDUX/CHANGED` to prevent unregistered actions triggering a `fetch()` and then a `render()` in components. I believe it would be better to export that name so I don't need to care about future changes.

Thanks

**Comment by zhongqf** [comment]
@tungv Thank you for using this package and sorry for the late reply.

I do not really understand why you need `@@METEORREDUX/CHANGED` to be exposed.
Do you want to prevent state changes except only when the `@@METEORREDUX/CHANGED` action be fired?
But in your code above, every `Todos.insert` or `Todos.remove` will cause a `@@METEORREDUX/CHANGED` action to be fired.

And, by the way, the second parameter of `bindReactiveData` should be a function which returns **object**, otherwise you will get an error.
